import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

import { TrpcProvider } from "@/utils/trpc-provider";
import getCurrentUser from "@/actions/getCurrentUser";
import { ThemeProvider } from "@/providers/theme-provider";

import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar/navbar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import ClientOnly from "@/components/ClientOnly";
import AuthContext from "./context/AuthContext";
import { redirect } from "next/navigation";
import NeedAdminPage from "./(routes)/needs-admin/page";

const PoppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="es">
      <body className={PoppinsFont.className}>
        <TrpcProvider>
          <AuthContext>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <ClientOnly>
                <Toaster />
                <LoginModal />
                <RegisterModal />
              </ClientOnly>
              {currentUser?.admin && <Navbar currentUser={currentUser} />}
              <div
                className={`container ${currentUser?.admin ? "lg:py-3" : ""}`}
              >
                {children}
              </div>
            </ThemeProvider>
          </AuthContext>
        </TrpcProvider>
      </body>
    </html>
  );
}
